services:
  - type: web
    name: reservation-salles
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: reservation-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: reservation-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: reservation-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: reservation-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: reservation-db
          property: password

databases:
  - name: reservation-db
    databaseName: reservation_salles
    user: reservation_user
    plan: free